IF NOT DEFINED JAVA_HOME (SET JAVA_HOME=%~dp0jdk1.8.0_91)
IF NOT DEFINED GROOVY_HOME (SET GROOVY_HOME=%~dp0groovy-2.5.0)
IF x%PATH:GROOVY=%==x%PATH% (SET PATH=%PATH%%GROOVY_HOME%\bin;)
IF x%PATH:Java=%==x%PATH% (SET PATH=%PATH%%JAVA_HOME%\bin;)